package:
  name: practice
  version: 0.0.4

about:
  author : pyt3r
  license_file: LICENSE
  summary: a package for practicing problems

source:
  path: ..

build:
  noarch: python
  entry_points:
    - practice-entry-point = practice.scripts.hello:world

requirements:
  build:
    - python=3.8
    - pyyaml

  run:
    - python
